regions = {
  "Pomurska": "Pomurska",
  "Podravska": "Podravska",
  "Koroška": "Koroška",
  "Savinjska": "Savinjska",
  "Zasavska": "Zasavska",
  "Posavska": "Posavska",
  "JugovzhodnaSlovenija": "Jugovzhodna Slovenija",
  "Osrednjeslovenska": "Osrednjeslovenska",
  "Gorenjska": "Gorenjska",
  "PrimorskoNotranjska": "Primorsko-notranjska",
  "Goriška": "Goriška",
  "Primorska": "Primorska",
}

water_levels = {
    "Reka - Škocjan": regions["Pomurska"],
    "Dreta - Kraše": regions["Savinjska"],
    "Drava - Črneče": regions["Koroška"],
    "Lijak - Volčja Draga": regions["Goriška"],
    "Rižana - Dekani": regions["Primorska"],
    "Soča - Kršovec": regions["Goriška"],
    "Kolpa - Sodevci": regions["JugovzhodnaSlovenija"],
    "Kokra - Kranj": regions["Gorenjska"],
    "Močilnik - Podnanos": regions["Primorska"],
    "Paka - Šoštanj": regions["Savinjska"],
    "Tržiška Bis. - Preska": regions["Gorenjska"],
    "Vipava - Zalošče": regions["Goriška"],
    "Bača - Bača pri Modreju": regions["Goriška"],
    "Suhodolnica - Stari trg": regions["Podravska"],
    "Drava - Zavrč": regions["Podravska"],
    "Mislinja - Otiški Vrh": regions["Savinjska"],
    "Vipava - Dolenje": regions["Goriška"],
    "Nanoščica - Mali otok": regions["PrimorskoNotranjska"],
    "Kamniška B. - Kamnik": regions["Osrednjeslovenska"],
    "Poljanska Sora - Zminec": regions["Gorenjska"],
    "Sava Boh. - Sv. Janez": regions["Gorenjska"],
    "Dravinja - Zreče": regions["Savinjska"],
    "Rača - Podrečje": regions["Osrednjeslovenska"],
    "Sava Dol. - Kranjska Gora": regions["Gorenjska"],
    "Pesnica - Ranca": regions["Koroška"],
    "Rižana - Kubed": regions["Primorska"],
    "Molja - Zarečica": regions["Primorska"],
    "Jadransko morje - boja Debeli Rtič": regions["Primorska"],
    "Sotla - Rogatec": regions["Savinjska"],
    "Radešca - Meniška vas": regions["JugovzhodnaSlovenija"],
    "Sava - Jesenice/Dol.": regions["Gorenjska"],
    "Pivka - Prestranek": regions["PrimorskoNotranjska"],
    "Savinja - Laško": regions["Zasavska"],
    "Sava Dol. - Blejski most": regions["Gorenjska"],
    "Cerknica - Cerkno": regions["Gorenjska"],
    "Trebuša - Dol. Trebuša": regions["Goriška"],
    "Sava Dol. - Jesenice": regions["Gorenjska"],
    "Idrijca Kanal - Podroteja": regions["Gorenjska"],
    "Sava - Radovljica": regions["Gorenjska"],
    "Hubelj - Ajdovščina": regions["Goriška"],
    "Nevljica - Nevlje": regions["Osrednjeslovenska"],
    "Drava - Borl": regions["Podravska"],
    "Prečna - Prečna": regions["JugovzhodnaSlovenija"],
    "Tolminka - Tolmin": regions["Goriška"],
    "Šujica - Razori": regions["Osrednjeslovenska"],
    "Sevnična - Metni vrh": regions["Posavska"],
    "Rogatnica - Podlehnik": regions["Podravska"],
    "Sava - Hrastnik": regions["Zasavska"],
    "Branica - Branik": regions["Primorska"],
    "Bohinjsko j. - Sv. Duh": regions["Gorenjska"],
    "Ložnica - Sp.Ložnica": regions["Podravska"],
    "Dravinja - Videm": regions["Podravska"],
    "Malenščica - Malni": regions["PrimorskoNotranjska"],
    "Sora - Suha": regions["Osrednjeslovenska"],
    "Sava - Medno": regions["Osrednjeslovenska"],
    "Oplotnica - Perovec": regions["Savinjska"],
    "Rača - Vir": regions["Osrednjeslovenska"],
    "Radulja - Škocjan": regions["JugovzhodnaSlovenija"],
    "Sava Boh. - Bodešče": regions["Gorenjska"],
    "Ljubija - Verd": regions["Osrednjeslovenska"],
    "Dravinja - Loče": regions["Savinjska"],
    "Jadransko morje - Koper": regions["Primorska"],
    "Paka - Velenje": regions["Koroška"],
    "Ložnica - Levec": regions["Savinjska"],
    "Cerkniščica - Cerknica": regions["Gorenjska"],
    "Reka - Neblo": regions["Goriška"],
    "Sava - Čatež": regions["Posavska"],
    "Kolpa - Petrina": regions["JugovzhodnaSlovenija"],
    "Drava - Ptuj": regions["Podravska"],
    "Sava - Šentjakob": regions["Osrednjeslovenska"],
    "Hudinja - Polže": regions["Savinjska"],
    "Ižica - Ig": regions["Osrednjeslovenska"],
    "Rakitnica - Blate": regions["JugovzhodnaSlovenija"],
    "Učja - Žaga": regions["Goriška"],
    "Savinja - Medlog": regions["Savinjska"],
    "Mura - Gor. Radgona": regions["Pomurska"],
    "Višnjica - Ivančna Gorica": regions["Osrednjeslovenska"],
    "Stržen - Dol. Jezero": regions["PrimorskoNotranjska"],
    "Kučnica - Cankova": regions["Pomurska"],
    "Selška Sora - Železniki": regions["Gorenjska"],
    "Savinja - Solčava": regions["Savinjska"],
    "Selška Sora - Vešter": regions["Gorenjska"],
    "Kobiljski p. - Kobilje": regions["Pomurska"],
    "Savinja - Vel. Širje": regions["Zasavska"],
    "Jezernica - Mlino": regions["Gorenjska"],
    "Vogršček - Bezovljak": regions["Goriška"],
    "Bistrica - Zagaj": regions["Posavska"],
    "Gradaščica - Dvor": regions["Osrednjeslovenska"],
    "Sava - Okroglo": regions["Gorenjska"],
    "Ljubljanica - Moste": regions["Osrednjeslovenska"],
    "Grosupeljščica - Mlačevo": regions["Osrednjeslovenska"],
    "Bistra - Bistra": regions["Osrednjeslovenska"],
    "Logaščica - Logatec": regions["Osrednjeslovenska"],
    "Savinja - Celje brv": regions["Savinjska"],
    "Ribnica - Prigorica": regions["JugovzhodnaSlovenija"],
    "Radoljna - Ruta": regions["Podravska"],
    "Sotla - Rakovec": regions["Savinjska"],
    "Lahinja - Gradac": regions["JugovzhodnaSlovenija"],
    "Vipava - Vipava": regions["Goriška"],
    "Hudinja - Škofja vas": regions["Savinjska"],
    "Poljanska Sora - Žiri": regions["Gorenjska"],
    "Sava - Litija": regions["Zasavska"],
    "Ljubljanica - Vrhnika": regions["Osrednjeslovenska"],
    "Temenica-Rožni Vrh": regions["JugovzhodnaSlovenija"],
    "Pšata - Topole": regions["Osrednjeslovenska"],
    "Soča - Solkan": regions["Goriška"],
    "Dravinja - Makole": regions["Savinjska"],
    "Koren - Nova Gorica": regions["Goriška"],
    "Borovniščica - Borovnica": regions["Osrednjeslovenska"],
    "Meža - Otiški vrh": regions["Koroška"],
    "Kolpa - Metlika": regions["JugovzhodnaSlovenija"],
    "Radovna - Podhom": regions["Gorenjska"],
    "Nadiža - Potoki": regions["Goriška"],
    "Bistrica - Sodražica": regions["JugovzhodnaSlovenija"],
    "Ledava - Čentiba": regions["Pomurska"],
    "Reka - Trnovo": regions["Osrednjeslovenska"],
    "Bistrica - Il. Bistrica": regions["PrimorskoNotranjska"],
    "Ledava - Polana": regions["Pomurska"],
    "Sora - Medvode": regions["Osrednjeslovenska"],
    "Savica - Ukanc": regions["Gorenjska"],
    "Voglajna - Celje": regions["Savinjska"],
    "Krka - Soteska": regions["JugovzhodnaSlovenija"],
    "Gradaščica - Bokalce": regions["Osrednjeslovenska"],
    "Velunja - Gaberke": regions["Savinjska"],
    "Bistrica - Muta": regions["Koroška"],
    "Kožbanjšček - Neblo": regions["Goriška"],
    "Lipnica - Ovsiše": regions["Gorenjska"],
    "Soča - Kobarid": regions["Goriška"],
    "Ivanjševski p. - Središče": regions["Podravska"],
    "Medija - Zagorje": regions["Zasavska"],
    "Jadransko morje - boja Tržaski zaliv": regions["Primorska"],
    "Ledava - Nuskova": regions["Pomurska"],
    "Reka - Trpčane": regions["Primorska"],
    "Voglajna - Črnolica": regions["Savinjska"],
    "Savinja - Letuš": regions["Savinjska"],
    "Reka - Cerkvenikov mlin": regions["Osrednjeslovenska"],
    "Kokra - Kokra": regions["Gorenjska"],
    "Blejsko jezero - Mlino": regions["Gorenjska"],
    "Badaševica - Šalara": regions["Primorska"],
    "Mislinja - Dovže": regions["Koroška"],
    "Krka - Podbočje": regions["Posavska"],
    "Gračnica - Vodiško": regions["Zasavska"],
    "Mirna - Martinja vas": regions["JugovzhodnaSlovenija"],
    "Vipava - Miren": regions["Goriška"],
    "Unica - Hasberg": regions["PrimorskoNotranjska"],
    "Polskava - Tržec": regions["Podravska"],
    "Meža -  Črna": regions["Koroška"],
    "Pšata - Loka": regions["Savinjska"],
    "Drnica - Pišine": regions["Savinjska"],
    "Savinja - Nazarje": regions["Savinjska"],
    "Krka - Podbukovje": regions["Posavska"],
    "Mirna - Jelovec": regions["Posavska"],
    "Pesnica - Zamušani": regions["Podravska"],
    "Ščavnica - Pristava": regions["Pomurska"],
    "Dragonja - Podkaštel": regions["Primorska"],
    "Ljubljanica - Kamin": regions["Osrednjeslovenska"],
    "Lučnica - Luče": regions["Savinjska"],
    "Sopota - Žebnik": regions["Primorska"],
    "Idrijca - Podroteja": regions["Primorska"],
    "Pesnica - Gočova": regions["Podravska"],
    "Velika Krka - Hodoš": regions["JugovzhodnaSlovenija"],
    "Martjanski p. - Martjanci": regions["Pomurska"],
    "Idrijca - Hotešk": regions["Primorska"],
    "Mestinjščica - Sodna vas": regions["Savinjska"],
    "Mura - Petanjci": regions["Pomurska"],
    "Krka - G. Gomila": regions["Posavska"],
    "Stržen - Gor. Jezero": regions["Primorska"],
    "Rinža - Livold": regions["Primorska"],
    "Rašica - Rašica": regions["Osrednjeslovenska"],
    "Bolska - Dolenja vas": regions["Osrednjeslovenska"],
    "Mostnica - Stara Fužina": regions["Gorenjska"],
    "Jadransko morje - boja Piran (NIB)": regions["Primorska"],
    "Iška - Iška vas": regions["Osrednjeslovenska"],
    "Paka - Rečica": regions["Savinjska"],
    "Kamniška B. - Bišče": regions["Osrednjeslovenska"],
    "Idrija - Golo Brdo": regions["Primorska"],
    "Soča - Log Čezsoški": regions["Primorska"],
    "Bistrica - Boh. Bistrica": regions["Osrednjeslovenska"],
    "Pivka - Postojnska jama": regions["Primorska"],
    "Kamniška B. - Vir": regions["Osrednjeslovenska"]
}     